### REQUEST JWT TOKEN
POST http://localhost:8080/monitor/api/auth/login
Content-Type: application/json
Accept: application/json

{ "username": "mario", "password": "123" }

### Get user's data
GET http://localhost:8080/monitor/api/auth/admin
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzEyMjk2MCwiZXhwIjoxNzM3MTI2NTYwfQ.8kr3Xlvr_q5usyY7HLahWTgy2rb4U54iqE_W4g7FyWk_A3yJbCKesvecHug9oupc


#########################
###### ENCOMENDAS #######
#########################
### EP01. Sistema regista uma nova encomenda
POST http://localhost:8080/monitor/api/encomendas/
Content-Type: application/json

{
  "encomendaId": 212,
  "clientUsername": "ricardo",
  "estado": "pendente"
}

### EP02
POST http://localhost:8080/monitor/api/volumes/2/produtos
Content-Type: application/json

{
  "productId": "IPHONE-14",
  "quantidade": 2
}

### EP03. Sistema consulta dados de uma encomenda existente
GET http://localhost:8080/monitor/api/encomendas/123
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJtYXJpbyIsImlhdCI6MTczNzIyNjg1NSwiZXhwIjoxNzM3MjMwNDU1fQ.YB2j6c31l2dTJsVzCHs3H5akuUVf61ZSocDZON7_DzRM9M9xDz9StWHFOWJcaLqo



### EP08 - Obter Todas as Encomendas
GET http://localhost:8080/monitor/api/encomendas
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzIyNjc2NiwiZXhwIjoxNzM3MjMwMzY2fQ.fy-Pg_jXeKUURbkxLHXW1Bb5avz90VhUx2uaW45E76ogYDBQnUmJK4rI-pgWHg3B



### EP10 – Atualizar Estado de uma Encomenda
PATCH http://localhost:8080/monitor/api/encomendas/123/estado
Content-Type: application/json

{
  "estado": "entregue"
}

### EP11 - Histórico de atualizações de estado da encomenda
GET http://localhost:8080/monitor/api/encomendas/historico
Accept: application/json


### all orders history
GET http://localhost:8080/monitor/api/encomendas/123/historico
Accept: application/json

### delete order by id
DELETE http://localhost:8080/monitor/api/encomendas/123
######################
###### VOLUMES #######
######################

### EP09 – Ver Produtos de um Volume
###

### get all volumes
GET http://localhost:8080/monitor/api/volumes

### insert package in volume
POST http://localhost:8080/monitor/api/volumes/1/packages/1

### Create a new volume
POST http://localhost:8080/monitor/api/volumes
Content-Type: application/json

{
  "id": 87,
  "volumeName": "New Volume TESTE"
}

### Get a specific volume
GET http://localhost:8080/monitor/api/volumes/1
Accept: application/json
#######################
###### PRODUTOS #######
#######################
### EP05 - Obter dados sobre todos os produtos
GET http://localhost:8080/monitor/api/produtos
Accept: application/json

### Get All Packages
GET http://localhost:8080/monitor/api/embalagens/
Accept: application/json

### Create a new product
POST http://localhost:8080/monitor/api/products/
Content-Type: application/json

{
  "productId": 23311,
  "productName": "Testadeee Product",
  "productType": "Elecctraaonics"
}

### Get product by id
GET http://localhost:8080/monitor/api/products/1
Accept: application/json

### update product by id
PUT http://localhost:8080/monitor/api/products/1
Content-Type: application/json

{
  "productName": "Updated Product Name",
  "productType": "Updated Product Type"
}

### delete product by id
DELETE http://localhost:8080/monitor/api/products/2

#####################
###### SENSOR #######
#####################
### EP04. Sensor envia o último valor lido para o sistema
POST http://localhost:8080/monitor/api/sensors
Content-Type: application/json

{
  "id": 1,
  "valor": 20.5
}

### EP06 - Obter o Último Valor Obtido por um Sensor
GET http://localhost:8080/monitor/api/sensors/1
Accept: application/json

### EP07 - Obter Histórico de Dados de um Sensor
GET http://localhost:8080/monitor/api/sensor/1/history
Accept: application/json

### EP12 – Apresentar todos os sensores
GET http://localhost:8080/monitor/api/sensors

### EP14 ---- A LOGICA DESTE ENDPOINT JÁ É FEITA NO ENDPOINT "associate sensor to volume" - APAGAR (?)
PATCH http://localhost:8080/monitor/api/sensors/5/estado
Content-Type: application/json

{
  "status": "Active"
}

### associate sensor to volume
POST http://localhost:8080/monitor/api/volumes/20/sensors/4

######################
###### PACKAGE #######
######################

### Create a new package
POST http://localhost:8080/monitor/api/packages/
Content-Type: application/json

{
  "packageId": "pkgaatessssst",
  "packageType": "Electronics"
}

### get package by id
GET http://localhost:8080/monitor/api/packages/{id}
Accept: application/json

### update package by id
PUT http://localhost:8080/monitor/api/packages/1
Content-Type: application/json

{
  "packageType": "Updated Package Type"
}

### delete package by id
DELETE http://localhost:8080/monitor/api/packages/pkgaatessssst

#####################
###### CLIENT #######
#####################

### Login as an admin
POST http://localhost:8080/monitor/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "admin",
  "password": "123"
}

### Login as a client
POST http://localhost:8080/monitor/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "ricardo",
  "password": "123"
}

### Get all clients
GET http://localhost:8080/monitor/api/clientes
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzE0MDA0MCwiZXhwIjoxNzM3MTQzNjQwfQ.oLrE9ItYiDMR8uGXvzjA0hKefQijF2PJaH7szWsuHRXy-OD8ZV4f8tkuRubD3hbj


### Get all clients' orders
GET http://localhost:8080/monitor/api/clientes/ricardo/encomendas
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzEzOTY0MiwiZXhwIjoxNzM3MTQzMjQyfQ.f5EUCDyxLtADI82pvMgz2AB_jUU_YSBZGSOaDmBbdWuRPOPVyRTjCrTqFm3NY6mv


